SpMarket/SpMarket/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^user/',include('sp_user.urls',namespace='sp_user')),

]

SpMarket/apps/sp_cart/urls.py
from django.conf.urls import url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
]

SpMarket/apps/sp_goods/urls.py
from django.conf.urls import url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
]

SpMarket/apps/sp_order/urls.py
from django.conf.urls import url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
]

SpMarket/apps/sp_user/urls.py
from django.conf.urls import url
from sp_user.views import (LoginView,
                           RegisterView,
                           ForgetPassView,
                           MemeberView,
                           InfomationView,
                           )

urlpatterns = [
    url(r'^login/$', LoginView.as_view(), name="login"),  # 登陆
    url(r'^register/$', RegisterView.as_view(), name="register"),  # 注册
    url(r'^forget/$', ForgetPassView.as_view(), name="forget"),  # 忘记密码
    url(r'^member/$', MemeberView.as_view(), name="member"),  # 个人中心
    url(r'^info/$', InfomationView.as_view(), name="info"),  # 个人资料
]

SpMarket/apps/sp_cart/models.py
from django.db import models

# Create your models here.

SpMarket/apps/sp_goods/models.py
from django.db import models

# Create your models here.

SpMarket/apps/sp_order/models.py
from django.db import models

# Create your models here.

SpMarket/apps/sp_user/models.py
from django.db import models

from db.base_model import BaseModel
from django.core.validators import RegexValidator


class SpUser(BaseModel):
    """
        用户表
    """
    sex_choices = (
        (1, "男"),
        (2, "女"),
    )
    phone = models.CharField(max_length=11,
                             verbose_name="手机号码",
                             validators=[
                                 RegexValidator(r'^1[3-9]\d{9}$',"手机号码格式错误!")
                             ])
    nickname = models.CharField(max_length=50, null=True, blank=True, verbose_name="昵称")
    password = models.CharField(max_length=32, verbose_name="密码")
    gender = models.SmallIntegerField(choices=sex_choices, default=1, verbose_name="性别")
    school_name = models.CharField(max_length=50, null=True, blank=True, verbose_name="学校")
    hometown = models.CharField(max_length=50, null=True, blank=True, verbose_name="家乡")
    birth_of_date = models.DateField(null=True, blank=True, verbose_name="出生日期")
    address = models.CharField(max_length=255, null=True, blank=True, verbose_name="详细位置")

    def __str__(self):
        return self.phone

    class Meta:
        db_table = "sp_user"
        verbose_name = "用户管理"
        verbose_name_plural = verbose_name

SpMarket/apps/sp_user/forms.py
from django import forms

from sp_user.helper import set_password
from sp_user.models import SpUser

"""
    普通的form


    modelform

"""


class RegisterModelForm(forms.ModelForm):
    """注册表单, 验证"""
    # 单独添加字段
    password1 = forms.CharField(max_length=16,
                                min_length=6,
                                error_messages={
                                    'required': '密码必填',
                                    'max_length': '密码长度不能大于16个字符',
                                    'min_length': '密码长度必须大于6个字符',
                                }
                                )
    password2 = forms.CharField(error_messages={'required': "确认密码必填"})

    class Meta:
        model = SpUser
        # 需要验证的字段
        fields = ['phone', ]

        error_messages = {
            "phone": {
                "required": "手机号码必须填写!"
            }
        }

    # 单独清洗(验证)
    def clean_password2(self):
        # 验证两个密码是否一致
        pwd1 = self.cleaned_data.get('password1')
        pwd2 = self.cleaned_data.get('password2')

        if pwd1 and pwd2 and pwd1 != pwd2:
            # 确认密码错误
            raise forms.ValidationError("两次密码输入不一致!")
        return pwd2

    def clean_phone(self):
        # 验证手机号码是否唯一
        phone = self.cleaned_data.get('phone')
        rs = SpUser.objects.filter(phone=phone).exists()  # 返回bool
        if rs:
            raise forms.ValidationError("手机号码已经被注册")
        return phone


class LoginModelForm(forms.ModelForm):
    """登陆的form表单"""

    class Meta:
        model = SpUser
        fields = ['phone', 'password']

        error_messages = {
            'phone': {
                "required": "手机号码必须填写!"
            },
            'password': {
                "required": "密码必须填写!"
            }
        }

        widgets = {  # 样式
            'phone': forms.TextInput(attrs={"class": "login-name", "placeholder": '请输入手机号'}),
            'password': forms.PasswordInput(attrs={"class": "login-password", "placeholder": '请输入密码'}),
        }

    def clean(self):  # 综合校验
        cleaned_data = self.cleaned_data
        # 获取用手机和密码
        phone = cleaned_data.get('phone')
        password = cleaned_data.get('password')
        # 验证手机号码是否存在
        if all([phone, password]):
            # 根据手机号码获取用户
            try:
                user = SpUser.objects.get(phone=phone)
            except SpUser.DoesNotExist:
                raise forms.ValidationError({"phone": "该用户不存在!"})

            # 判断密码是否正确
            if user.password != set_password(password):
                raise forms.ValidationError({"password": "密码填写错误!"})

            # 正确
            # 将用户信息保存到cleaned_data中
            cleaned_data['user'] = user
            return cleaned_data
        else:
            return cleaned_data

SpMarket/apps/sp_cart/views.py
from django.shortcuts import render

# Create your views here.

SpMarket/apps/sp_goods/views.py
from django.shortcuts import render

# Create your views here.

SpMarket/apps/sp_order/views.py
from django.shortcuts import render

# Create your views here.

SpMarket/apps/sp_user/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.views import View

from sp_user.forms import RegisterModelForm, LoginModelForm
from sp_user.helper import set_password, login
from sp_user.models import SpUser

"""
    开始定义视图:
    1. 函数
    2. 视图类
        a. 定义一个类, 继承 View
        b. 定义方法, 方法名一定要和请求方式名同名(小写 get,post)
        c. 所有的方法都第一个参数和第二个都是固定: self,request
"""


class LoginView(View):
    """登陆"""
    def get(self, request):
        # 创建登陆表单对象
        login_form = LoginModelForm()
        return render(request, "sp_user/login.html", {'form': login_form})

    def post(self, request):
        # 接收数据
        data = request.POST
        # 验证数据
        login_form = LoginModelForm(data)
        if login_form.is_valid():
            # 验证成功后将登陆标识放到session中
            user = login_form.cleaned_data.get('user')
            # 调用登陆的方法,放在helper模块中的
            login(request, user)
            # 跳转到用户中心页面
            return redirect('sp_user:member')
        else:
            return render(request, "sp_user/login.html", {'form': login_form})


class RegisterView(View):
    """注册"""

    def get(self, request):
        return render(request, "sp_user/reg.html")

    def post(self, request):
        # 处理
        # 1. 接收
        data = request.POST
        # 2. 处理
        # 验证是否合法
        form = RegisterModelForm(data)
        if form.is_valid():
            # 处理,保存到数据库
            data = form.cleaned_data
            # 密码需要加密
            password = data.get('password2')
            # 调用方法帮助我对密码进行加密
            password = set_password(password)
            # 保存到数据库
            SpUser.objects.create(phone=data.get('phone'), password=password)

            # 成功跳转到登陆页面
            return redirect("sp_user:login")
        else:
            # 传递错误信息到页面
            context = {
                "errors": form.errors,
            }
            # 3. 响应
            return render(request, "sp_user/reg.html", context)


class ForgetPassView(View):
    """找回密码"""

    def get(self, request):
        return render(request, "sp_user/forgetpassword.html")

    def post(self, request):
        pass


class MemeberView(View):
    """个人中心"""

    def get(self, request):
        context = {
            "phone": request.session.get('phone')
        }
        return render(request, 'sp_user/member.html',context)

    def post(self, request):
        pass


class InfomationView(View):
    """个人资料"""

    def get(self, request):
        return render(request, 'sp_user/infor.html')

    def post(self, request):
        pass

SpMarket/templates/sp_user/forgetpassword.html
{% extends 'public/base.html' %}
{% load static %}

{% block header_title %}
    忘记密码
{% endblock %}


{% block content %}
    <input type="text" name="mobile" placeholder="请输入手机号" class="login-password">
    <div class="yzm">
        <input type="text" class="reg-yzm" placeholder="输入验证码"/>
        <input type="button" class="yzm-hq" value="获取验证码"/>
    </div>
    <input type="password" name="password" placeholder="请输入密码" class="login-password">
    <input type="password" name="password" placeholder="确认密码" class="login-name">
    <input type="button" class="login-btn" value="立即提交">
{% endblock %}

SpMarket/templates/sp_user/infor.html
{% extends 'public/base.html' %}
{% load static %}

{% block header_title %}
    注册
{% endblock %}

{% block content %}
	    <div style="height: 49px;"></div>
	    <ul class="safty1">
	    	<li>
	    		<a href="">
	    			<i style="margin-top: 25px;">头像</i>
	    			<div class="infor-pic">
	    				<img src="{% static 'images/infortx.png' %}" />
	    			</div>
	    		</a>
	    	</li>
	    	<li>
	    		<a href="">
	    			<i>昵称</i>
	    			<input class="infor-tele" placeholder="默契"/>
	    		</a>
	    	</li>
	    	<li>
	    		<a href="">
	    			<i>性别</i>
	    			<i class="infor-tele">
	    				<label class="am-radio-inline">
				          <input type="radio" name="radio10" checked="checked" value="1" data-am-ucheck>男
				        </label>
				        <label class="am-radio-inline">
				          <input type="radio" name="radio10" value="1" data-am-ucheck>女
				        </label>
	    			</i>
	    		</a>
	    	</li><li>
	    		<a href="">
	    			<i>生日</i>
                    <input class="infor-tele" placeholder="出生日期"/>
	    		</a>
	    	</li>
	    </ul>
	    <div style="height: 10px; background: #efefef;"></div>
	     <ul class="safty1">
	    	<li>
	    			<i>学校</i>
	    			<input class="infor-tele" placeholder="就读于哪个学校"/>
	    	</li>
	    	<li>
	    			<i>位置</i>
	    			<input class="infor-tele" placeholder="详细地址"/>
	    	</li>
	    	<li>
	    			<i>故乡</i>
                    <input class="infor-tele" placeholder="来自哪里"/>
	    	</li>
	    	<li>
	    			<i>手机</i>
                    <input class="infor-tele" placeholder="13012345678"/>
	    	</li>
	    </ul>
{% endblock %}
{#	    <script src="{% static 'js/jquery.min.js' %}"></script>#}
{#        <script src="{% static 'js/amazeui.min.js' %}"></script>#}

SpMarket/templates/sp_user/login.html
{% extends 'public/base.html' %}
{% load static %}
{% block header_title %}
    登录
{% endblock %}


{% block content %}

    <form action="" method="post" novalidate>
        <div style="height: 3rem;"></div>
        {% csrf_token %}
        {{ form.phone }}<p class="am-text-danger">{{ form.errors.phone.0 }}</p>          {# 错误信息 #}
        {{ form.password }}<p class="am-text-danger">{{ form.errors.password.0 }}</p>    {# 错误信息 #}
        <input type="submit" class="login-btn" value="我要登录">
    </form>
    <div class="agree">
        <a href="{% url 'sp_user:register' %}">免费注册</a>
        <a href="{% url 'sp_user:forget' %}" class="forget">忘记密码？</a>
    </div>
    <div class="line"></div>
    <div class="line-text">第三方账号登录</div>
    <ul class="second-login">
        <li><a href=""><img src="{% static 'images/wxlogin.png' %}"/></a></li>
        <li><a href=""><img src="{% static 'images/qqlogin.png' %}"/></a></li>
        <li><a href=""><img src="{% static 'images/sinalog.png' %}"/></a></li>
    </ul>
{% endblock %}

SpMarket/templates/sp_user/member.html
{% extends 'public/base.html' %}
{% load static %}
{% block header_title %}
个人中心
{% endblock %}
{% block content %}
	    <div style="height: 49px;"></div>
	    <div class="member">
	    	<div class="mem-tit">15078921546
	    		<a href="step.html" class="step"><img src="{% static 'images/step.png' %}" width="26"/></a>
	    	</div>
	    	<div class="mem-pic">
		    	<div class="mem-pic-bg" style="background-image: url({% static 'images/memtx.png' %});"></div>
	    	</div>
	    	<ul class="member-menu">
			<li>
				<a href="records.html">
					<p class="yellow">0</p>
					<p class="black">帐户余额 </p>
				</a>
			</li>
            <li>
				<a href="integral.html">
					<p class="yellow">0</p>
					<p class="black">积分 </p>
				</a>
			</li>
			<li>
				<a href="yhq.html">
					<p class="yellow">0</p>
					<p class="black">优惠劵 </p>
				</a>
			</li>
			<li>
				<a href="collect.html">
					<p class="yellow">0</p>
					<p class="black">我的收藏 </p>
				</a>
			</li>
		</ul>
	    </div>
	    <div class="user-list">
		  	<div class="u-list-main">
		  		<img src="{% static 'images/order-pic.png' %}" width="27" />
		  		<span>我的购物订单</span>
		  		<a href="allorder.html">查看全部订单></a>
		  	</div>
		    <ul class="user-nav">
		    	<li><a href="allorder.html"> <img src="{% static 'images/1-icon.png' %}"> <p>待付款</p></a></li>
		    	<li><a href="allorder.html"> <img src="{% static 'images/1-icon1.png' %}"> <p>待收货</p></a></li>
		    	<li><a href="allorder.html"> <img src="{% static 'images/1-icon2.png' %}"> <p>待评价</p></a></li>
		    	<li><a href="allorder.html"> <img src="{% static 'images/1-icon3.png' %}"> <p>退换货</p></a></li>
		    </ul>
		    <div class="u-list-main">
		  		<img src="{% static 'images/order-my.png' %}" width="27" />
		  		<span>帐户与安全</span>
		  	</div>
		    <ul class="user-nav">
		    	<li><a href="infor.html"> <img src="{% static 'images/1-icon4.png' %}"> <p>个人资料</p></a></li>
		    	<li><a href="gladdress.html"> <img src="{% static 'images/1-icon5.png' %}"> <p>收货地址</p></a></li>
		    	<li><a href="saftystep.html"> <img src="{% static 'images/1-icon6.png' %}"> <p>安全设置</p></a></li>
		    	<li><a href="money.html"> <img src="{% static 'images/1-icon7.png' %}"> <p>我的钱包</p></a></li>
		    </ul>
	    </div>
	    <!--导航-->
 <ul class="sq-nav" style=" background: #fff; margin-top: 1rem; border-top: 1px solid #ddd;  border-bottom: 1px solid #ddd;">
      <li>
        <div class="am-gallery-item">
            <a href="job.html" class="">
              <img src="{% static 'images/m_03.png' %}" />
              <p>我要兼职</p>
            </a>
        </div>
      </li>
      <li>
        <div class="am-gallery-item">
            <a href="recommend.html" class="">
              <img src="{% static 'images/m_04.png' %}" />
              <p>推荐有奖</p>
            </a>
        </div>
      </li>
      <li>
        <div class="am-gallery-item">
            <a href="myrecommend.html" class="">
              <img src="{% static 'images/m_05.png' %}" />
              <p>我的推荐</p>
            </a>
        </div>
      </li>
      <li>
        <div class="am-gallery-item">
            <a href="" class="">
              <img src="{% static 'images/m_06.png' %}" />
              <p>我的佣金</p>
            </a>
        </div>
      </li>
      <li>
        <div class="am-gallery-item">
            <a href="yhq.html" class="">
              <img src="{% static 'images/m_02.png' %}" />
              <p>我的红包</p>
            </a>
        </div>
      </li>
      <li>
        <div class="am-gallery-item">
            <a href="message.html" class="">
              <img src="{% static 'images/m_07.png' %}" />
              <p>我的动态</p>
            </a>
        </div>
      </li>
      <li>
        <div class="am-gallery-item">
            <a href="javascript:;" class="index-qd">
              <img src="{% static 'images/m_08.png' %}" />
              <p>客服中心</p>
            </a>
        </div>
      </li>
      <li>
        <div class="am-gallery-item">
            <a href="" class="">
              <img src="{% static 'images/m_09.png' %}" />
              <p>安全退出</p>
            </a>
        </div>
      </li>
      </ul>
      </div>
    <!--客服中心-->
<div class="qd-box">
	<div class="popup-title">
			<span>客服中心</span>
			<div class="popup-close"><i class="iconfont">&#xe602</i></div>
	</div>
	<div class="dq-text">
		<a href="http://wpa.qq.com/msgrd?v=3&uin=123456789&site=qq&menu=yes">
			<img src="{% static 'images/contactqq.png' %}" width="50" />
			<p class="contactqq">联系QQ</p>
		</a>
		<a href="tel:0791-12345678">
			<img src="{% static 'images/contacttele.png' %}"  width="50" />
			<p class="contacttele">呼叫电话</p>
		</a>
	</div>
</div>

 <div style="height: 55px;"></div>
 <div data-am-widget="navbar" class="am-navbar am-cf am-navbar-default sq-foot am-no-layout" id="">
      <ul class="am-navbar-nav am-cf am-avg-sm-5">
          <li>
            <a href="index.html" class="">
                <span class="am-icon-home"></span>
                <span class="am-navbar-label">首页</span>
            </a>
          </li>
          <li>
            <a href="message.html" class="">
                <span class="am-icon-comments"></span>
                <span class="am-navbar-label">动态</span>
            </a>
          </li>
          <li>
            <a href="shopcart.html" class="">
                <span class="am-icon-shopping-cart"></span>
                <span class="am-navbar-label">购物车</span>
            </a>
          </li>
          <li>
            <a href="allorder.html" class="">
                <span class="am-icon-file-text"></span>
                <span class="am-navbar-label">订单</span>
            </a>
          </li>

          <li>
            <a href="member.html" class="curr">
                <span class="am-icon-user"></span>
                <span class="am-navbar-label">我的</span>
            </a>
          </li>
      </ul>
</div>

{% endblock %}


 
 

 

SpMarket/templates/sp_user/reg.html
{% extends 'public/base.html' %}
{% load static %}

{% block header_title %}
    <a href="" class="">注册</a>
{% endblock %}


{% block content %}
    <div style="height: 3rem;"></div>
    <form action="" method="post">
        {% csrf_token %}
        <input type="text" name="phone" placeholder="请输入手机号" class="login-name">
        <p class="am-text-danger">{{ errors.phone.0 }}</p>
        <input type="password" name="password1" placeholder="请输入密码" class="login-password">
        <p class="am-text-danger">{{ errors.password1.0 }}</p>
        <input type="password" name="password2" placeholder="确认密码" class="login-name">
        <p class="am-text-danger">{{ errors.password2.0 }}</p>
        <div class="yzm" style="margin-top: 1.5rem;">
            <input type="text" class="reg-yzm" placeholder="输入验证码"/>
            <input type="button" class="yzm-hq" value="获取验证码"/>
        </div>
        <input type="submit" class="login-btn" value="立即注册">
        <div class="agree">
            <input type="checkbox" name="checkbox" value="同意" checked="">&nbsp;同意
            <a href="" class="xy">《用户协议》</a>
            <div class="r-login">已有账号，请<a href="login.html" class="l-login">登录</a></div>
        </div>
    </form>
{% endblock %}